version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: AudensielScrap/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    environment:
      - MONGO_URL=mongodb+srv://cloe:Webscrap23@cluster0.qnvy73r.mongodb.net/?authMechanism=SCRAM-SHA-1
    # links:
    #   - mongo

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"

  # mongo:
  #   build:
  #     context: .
  #     dockerfile:  AudensielScrap/Dockerfile-mongo
  #   ports:
  #     - "27017:27017"


