# Generated by Django 4.1.7 on 2023-11-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetModele',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tweet', models.TextField()),
                ('like', models.IntegerField()),
            ],
        ),
    ]
