# Generated by Django 4.1.13 on 2023-12-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twittersearch", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TweetModele",
        ),
    ]
