"""
Django settings for AudensielScrap project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from mongoengine import connect
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-62f-3=v7_k3+kq=40j(%q)%u-e3goqiqv&ca)a^1p9&c*&*&*%'

<<<<<<< Updated upstream
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
=======
ALLOWED_HOSTS = [
    '.versel.app',
    'localhost',
    '127.0.0.1',
    '*'
]
>>>>>>> Stashed changes


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'twittersearch.apps.TwittersearchConfig',
    'djongo',
<<<<<<< Updated upstream
=======
    'corsheaders',
>>>>>>> Stashed changes
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AudensielScrap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'AudensielScrap', 'twittersearch', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AudensielScrap.wsgi.application'

<<<<<<< Updated upstream
=======
# Other security settings
# SECURE_SSL_REDIRECT = False
# SESSION_COOKIE_SECURE = False
>>>>>>> Stashed changes

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  # Add any other allowed origins
]

<<<<<<< Updated upstream
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'Tweets',
#         'CLIENT': {
#             'host': 'mongodb+srv://cloe:Webscrap23@cluster0.qnvy73r.mongodb.net/?authMechanism=SCRAM-SHA-1',
#             'name': 'TestFrontEnd',
#             'username': 'cloe',
#             'password': 'Webscrap23',
#             'authMechanism': 'SCRAM-SHA-1',
#         },
#     },
# }
connect(
    db='Tweets',
    username='cloe',
    password='Webscrap23',
    host='mongodb+srv://cloe:Webscrap23@cluster0.qnvy73r.mongodb.net/TestFrontEnd?authMechanism=SCRAM-SHA-1',
    authentication_source='admin',
    authentication_mechanism='SCRAM-SHA-1'
)
=======
>>>>>>> Stashed changes


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

<<<<<<< Updated upstream
STATIC_URL = '/static/'
=======
# Assuming BASE_DIR is defined in your settings.py
>>>>>>> Stashed changes

# Set the path to the static files directory of the React frontend
REACT_STATIC_DIR = os.path.join(BASE_DIR, 'frontend', 'build', 'static')

# Configure Django's static file settings
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    REACT_STATIC_DIR,
]

# Ensure Django serves static files in production
DEBUG = True
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
